// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelImport() {
  return window['go']['main']['DesktopApp']['CancelImport']();
}

export function ChooseCachePath() {
  return window['go']['main']['DesktopApp']['ChooseCachePath']();
}

export function ClearCache() {
  return window['go']['main']['DesktopApp']['ClearCache']();
}

export function Convert(arg1) {
  return window['go']['main']['DesktopApp']['Convert'](arg1);
}

export function ExportCurrencyHistory(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ExportCurrencyHistory'](arg1, arg2);
}

export function GetCurrencies() {
  return window['go']['main']['DesktopApp']['GetCurrencies']();
}

export function GetCurrencyHistory(arg1, arg2) {
  return window['go']['main']['DesktopApp']['GetCurrencyHistory'](arg1, arg2);
}

export function GetDashboard() {
  return window['go']['main']['DesktopApp']['GetDashboard']();
}

export function ImportRates(arg1) {
  return window['go']['main']['DesktopApp']['ImportRates'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['DesktopApp']['SaveSettings'](arg1);
}
