// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appcore} from '../models';
import {models} from '../models';
import {cache} from '../models';

export function CancelImport():Promise<boolean>;

export function ChooseCachePath():Promise<string>;

export function ClearCache():Promise<void>;

export function Convert(arg1:appcore.ConvertRequest):Promise<appcore.ConversionResult>;

export function ExportCurrencyHistory(arg1:string,arg2:string):Promise<string>;

export function GetCurrencies():Promise<Array<models.Currency>>;

export function GetCurrencyHistory(arg1:string,arg2:number):Promise<Array<cache.CurrencyHistoryEntry>>;

export function GetDashboard():Promise<appcore.Dashboard>;

export function ImportRates(arg1:appcore.ImportRequest):Promise<appcore.ImportSummary>;

export function SaveSettings(arg1:models.AppConfig):Promise<appcore.Dashboard>;
